version: "3.9"
services:
  qul:
    volumes:
      - qul_home:/home
      - /home/panajot/Workspace/qul:/repo
      - .:/workspace
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    user: ${USER}
    image: ${USER}/qt:latest
    container_name: qul
    devices:
      - /dev/bus/usb/:/dev/bus/usb/

  qul_stm32:
    profiles:
      - stm32
    volumes:
      - qul_home:/home
      - /home/panajot/Workspace/qul:/repo
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    privileged: true
    environment:
      # Run 'xhost local:root' before docker-compose if you want to run Gui apps as a root from container
      - DISPLAY=${DISPLAY}
    network_mode: host
    image: qt-srv-56.intra.qt.io/docker/qtformcu/ci-linux-runner-master-stm32cubef7-devenv:35
    container_name: qul_stm32
    devices:
      - /dev/bus/:/dev/bus/

  qul_fedora:
    profiles:
      - fedora
    volumes:
      - qul_home:/home
      - /home/panajot/Workspace/qul:/repo
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    image: ${USER}/qul_fedora:latest
    container_name: qul_fedora

volumes:
  qul_home:
