# install core
include(GNUInstallDirs)

# cmake-format: off
set(SETFINDER_CMAKE_INSTALL_PATH    "${CMAKE_INSTALL_PREFIX}/cmake")
set(SETFINDER_LIB_INSTALL_PATH      "${CMAKE_INSTALL_PREFIX}/lib")
set(SETFINDER_INCLUDE_INSTALL_PATH  "${CMAKE_INSTALL_PREFIX}/include")
# cmake-format: on

install(
  TARGETS core
  EXPORT SetFinderTargets
  DESTINATION ${SETFINDER_LIB_INSTALL_PATH}
  PUBLIC_HEADER DESTINATION ${SETFINDER_INCLUDE_INSTALL_PATH}/core
)

install(EXPORT SetFinderTargets DESTINATION ${SETFINDER_CMAKE_INSTALL_PATH}
        NAMESPACE ${CMAKE_PROJECT_NAME}::
)
