#!/bin/bash

JAVA_SDK=/workdir/sdk
ANDROID_ABIs=("x86" "arm64-v8a" "x86_64" "armeabi-v7a")

OpenCV_DIR=/workdir/OpenCV-android-sdk/sdk/native/jni
CMAKE_SYSTEM_NAME=Android
CMAKE_SYSTEM_VERSION=24
ANDROID_PLATFORM=android-24
CMAKE_ANDROID_ARCH_ABI=x86
ANDROID_NDK=${JAVA_SDK}/ndk/22.1.7171670
CMAKE_ANDROID_NDK=${JAVA_SDK}/ndk/22.1.7171670
CMAKE_TOOLCHAIN_FILE=${JAVA_SDK}/ndk/22.1.7171670/build/cmake/android.toolchain.cmake
# CMAKE_MAKE_PROGRAM=${JAVA_SDK}/cmake/3.18.1/bin/ninja
CMAKE_BUILD_TYPE=Debug


for ANDROID_ABI in ${ANDROID_ABIs[@]};
do
    echo ${ANDROID_ABI}
    CMAKE_ANDROID_ARCH_ABI=${ANDROID_ABI}
    INSTALL_DIR=${YUV_CONVERTER}/${ANDROID_ABI}
    BUILD_DIR=build_android/${ANDROID_ABI}

    cmake -S . -B ${BUILD_DIR} \
        -DDISABLE_TOOLS=ON \
        -DOpenCV_DIR=${OpenCV_DIR} \
        -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} \
        -DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME} \
        -DCMAKE_SYSTEM_VERSION=${CMAKE_SYSTEM_VERSION} \
        -DANDROID_PLATFORM=${ANDROID_PLATFORM} \
        -DANDROID_ABI=${ANDROID_ABI} \
        -DCMAKE_ANDROID_ARCH_ABI=${CMAKE_ANDROID_ARCH_ABI} \
        -DANDROID_NDK=${ANDROID_NDK} \
        -DCMAKE_ANDROID_NDK=${CMAKE_ANDROID_NDK} \
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} \
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        # -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM} \

    make -C ${BUILD_DIR} install
done
